import { Act } from "./action_traces";

// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Transactions {
    _id:                    string;
    trx_id:                 string;
    accepted:               boolean;
    actions:                Act[];
    context_free_actions:   any[];
    context_free_data:      any[];
    createdAt:              string;
    delay_sec:              number;
    expiration:             string;
    implicit:               boolean;
    max_cpu_usage_ms:       number;
    max_net_usage_words:    number;
    ref_block_num:          number;
    ref_block_prefix:       string;
    scheduled:              boolean;
    signatures:             any[];
    transaction_extensions: any[];
}
