// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Actions {
    _id:           string;
    action_num:    number;
    trx_id:        string;
    cfa:           boolean;
    account:       string;
    name:          string;
    authorization: Authorization[];
    data:          Data;
}

export interface Authorization {
    actor:      string;
    permission: string;
}

export interface Data {
    payer:    string;
    receiver: string;
    bytes:    number;
}
